spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-factory
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://mwk:mwk666@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
feign:
  hystrix:
    enabled: true
#响应时间，
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000