spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
 client:
    service-url:
      defaultZone: http://mwk:mwk666@localhost:8761/eureka
zuul:
  routes:
    microservice-provider-user-client: /user/**
      