spring:
  application:
    name: microservice-consumer-movie-feign
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://mwk:mwk666@localhost:8761/eureka
  instance:
    prefer-ip-address: true